[build]
  base = "front-end"
  publish = "out"
  command = "npm install --legacy-peer-deps --omit=dev && npm run build"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"
  REACT_APP_BACKEND_URL = "https://movie-booking-wrhs.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200