[build]
  base = "front-end"
  publish = "out"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"
  REACT_APP_BACKEND_URL = "https://movie-booking-wrhs.onrender.com"

# This proxies API calls to backend
[[redirects]]
  from = "/api/*"
  to = "https://movie-booking-wrhs.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { 
    Access-Control-Allow-Origin = "*",
    Access-Control-Allow-Credentials = "true"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200