import './globals.css';
import ClientProviders from "./ClientProviders";
import RootLayoutClient from './layout.client'; // Import the client layout

export const metadata = {
  title: 'Book a movie!',
  description: 'Generated by Next.js',
};

export default function RootLayoutServer({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {/* Now wrap the children inside RootLayoutClient */}
          <RootLayoutClient>{children}</RootLayoutClient>
        </ClientProviders>
      </body>
    </html>
  );
}
