// app/layout.server.tsx
import './globals.css';
import ClientProviders from "./ClientProviders";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayoutServer({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClientProviders>{children}</ClientProviders>
  );
}
