# Dockerfile.dev
FROM node:18

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copy the rest of the files
COPY . .

# Expose dev port
EXPOSE 3000

# Run in dev mode with HMR
CMD ["npm", "run", "dev"]
