[build]
  base = "front-end"
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  REACT_APP_BACKEND_URL = "https://movie-booking-wrhs.onrender.com"

[build.lifecycle]
  # This overrides the default install command
  onInstall = "./netlify-preinstall.sh"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200