[build]
  # Directory to publish (this should match the folder where your build output is)
  publish = "build"
  # Command to build your app (adjust if you're using yarn or have a different build script)
  command = "npm run build"

[build.environment]
  # Set environment variables here if needed (already available through Netlify UI, but you can set them here too)
  REACT_APP_BACKEND_URL = "https://movie-booking-wrhs.onrender.com"
  # Optionally specify the Node.js version you want Netlify to use
  NODE_VERSION = "16"

[[redirects]]
  # Ensure client-side routing works (like using React Router)
  from = "/*"
  to = "/index.html"
  status = 200