apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-booking-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-booking-backend
  template:
    metadata:
      labels:
        app: movie-booking-backend
    spec:
      containers:
        - name: backend
          image: 420366006197.dkr.ecr.ap-southeast-1.amazonaws.com/movie-booking-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: private-key
                  key: PRIVATE_KEY
            - name: CONTRACT_ADDRESS
              value: "0x37332F46FD252538c1063F18F3fB461e0d687c0F"  # replace with actual address
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: movie-booking-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
